from typing import Protocol
from uuid import UUID

from app.domain.entities.call import Call


class CallRepositoryPort(Protocol):
    async def get_by_id(self, call_id: UUID) -> Call | None: ...

    async def add(self, call: Call) -> Call: ...

    async def update(self, call: Call) -> Call: ...

    async def bulk_update(self, calls: list[Call]) -> None: ...

    async def list_all(self) -> list[Call]: ...

    async def list_by_provider_call_id(self, provider_call_id: str) -> list[Call]: ...

    async def list_by_sweep_id(self, sweep_id: UUID) -> list[Call]: ...

    async def get_last_call_for_facility(self, facility_id: UUID) -> Call | None: ...
